# Generated by Django 3.2.14 on 2022-08-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'HastTags',
                'verbose_name_plural': 'HashTags',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
