# Generated by Django 3.2.14 on 2022-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatar'),
        ),
    ]
